server:
  port : 8080
  servlet:
    session:
      timeout: 30d

app:
  authentication:
    webRedirect: ${AUTH_MOBILE_REDIRECT}
    mobileRedirect: ${AUTH_MOBILE_REDIRECT}
  oauth:
    redirectUrl: ${OAUTH_REDIRECT_URL}
    google:
      clientId: ${OAUTH_GOOGLE_CLIENTID}
      clientSerect: ${OAUTH_GOOGLE_SERECT}

spring:
  application:
    name: petfabula

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
      enabled: true
  server:
    tomcat:
      max-http-post-size: 10MB
      max-swallow-size: 30MB

  session:
    store-type: redis

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  redis:
    database: 0
    host: ${REDIS_HOST}
    port: 6379
    timeout: 60000

  data:
    elasticsearch:
      cluster-name: elasticsearch
      host: ${ES_HOST}
      port: 9300
      restport: 9200

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          quitwait: false
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST}

upload:
  imageUrl: ${UPLOAD_URL}

image:
  contentUrl: ${IMAGE_URL_PREFIX}